version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=bits
    volumes:
      - bits_pg_data:/bitnami/postgresql

  app:
    image: node:20.11.1
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - DATABASE_URL=postgresql://docker:docker@postgres:5432/bits
    command: sh -c "npm install && npm run typeorm migration:run -- -d src/data-source && npm run start"

volumes:
  bits_pg_data:
